Updating JaCoCo file path.
Error: No files were found with the provided path: build/reports/jacoco/test/html/. No artifacts will be uploaded.
Changing file path to: build/reports/jacoco/applicationCodeCoverageReport/html/
So that the report can hopefully be generated.